# Generated by Django 5.0.6 on 2024-06-16 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_petition_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='likes',
        ),
        migrations.AddField(
            model_name='petition',
            name='signed_users',
            field=models.ManyToManyField(blank=True, related_name='signed_petitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
