# Generated by Django 5.0.6 on 2024-06-16 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
